apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hypershift-operator
  namespace: hypershift
spec:
  lookupPolicy:
    local: true
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/hypershift/hypershift-operator:latest
    referencePolicy:
      type: Local
    importPolicy:
      scheduled: true
  - name: ci
    from:
      kind: DockerImage
      name: quay.io/hypershift/hypershift-operator:e43a80bb
    referencePolicy:
      type: Local
    importPolicy:
      scheduled: true
---
# this grants all authenticated users rights to pull images. We need this to allow
# pulling of the hypershift operator image from cluster namespaces, which happens
# in 4.10 for the utility containers.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hypershift-image-puller-binding
  namespace: hypershift
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:image-puller
subjects:
# this is the set of all authenticated users
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
# The CPO has a pull secret directly configured
# and it appears that that results in the SAs
# pull secret not being used anymore.
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
